package org.springboard.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@DynamoDBTable(tableName="UserQueue")
public class UserQueue {

    private String id;

    private UserStatus status;

    private String name;

    private String mobileNumber;

    private String email;
    private String comments;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute
    public UserStatus getStatus() {
        return status;
    }

    public void setStatus(UserStatus status) {
        this.status = status;
    }

    @DynamoDBAttribute
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute
    public String getMobileNumber() {
        return mobileNumber;
    }

    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }

    @DynamoDBAttribute
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @DynamoDBAttribute
    public String getComments() {
        return comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public UserQueue() {

    }

    public UserQueue(UserStatus status, String name, String mobileNumber, String email, String comments) {
        this.status = status;
        this.name = name;
        this.mobileNumber = mobileNumber;
        this.email = email;
        this.comments = comments;
    }

    public UserQueue(String id, UserStatus status, String name, String mobileNumber, String email, String comments) {
        this.id = id;
        this.status = status;
        this.name = name;
        this.mobileNumber = mobileNumber;
        this.email = email;
        this.comments = comments;
    }

    @Override
    public String toString() {
        return "UserQueue{" +
                "id='" + id + '\'' +
                ", status=" + status +
                ", name='" + name + '\'' +
                ", mobileNumber='" + mobileNumber + '\'' +
                ", email='" + email + '\'' +
                ", comments='" + comments + '\'' +
                '}';
    }
}
